/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0c0e11",
        "on-surface": "#e2e2e6",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#004119",
        "surface-container-high": "#282a2d",
        "on-tertiary-fixed": "#001a42",
        "on-background": "#e2e2e6",
        "surface-tint": "#ffb3ad",
        "surface": "#111317",
        "secondary-container": "#00b954",
        "tertiary-fixed": "#d8e2ff",
        "on-tertiary-fixed-variant": "#004395",
        "surface-container": "#1e2023",
        "error-container": "#93000a",
        "secondary": "#4ae176",
        "on-secondary-fixed-variant": "#005321",
        "on-tertiary": "#002e6a",
        "tertiary": "#adc6ff",
        "outline": "#ab8986",
        "primary-fixed": "#ffdad7",
        "on-primary-fixed-variant": "#930013",
        "surface-variant": "#333538",
        "on-tertiary-container": "#00285d",
        "on-primary": "#68000a",
        "surface-bright": "#37393d",
        "tertiary-fixed-dim": "#adc6ff",
        "primary": "#ffb3ad",
        "inverse-primary": "#b91a24",
        "on-surface-variant": "#e4beba",
        "primary-fixed-dim": "#ffb3ad",
        "primary-container": "#ff5451",
        "tertiary-container": "#4d8eff",
        "on-error": "#690005",
        "secondary-fixed": "#6bff8f",
        "on-secondary": "#003915",
        "on-primary-fixed": "#410004",
        "secondary-fixed-dim": "#4ae176",
        "surface-container-highest": "#333538",
        "inverse-surface": "#e2e2e6",
        "background": "#111317",
        "surface-dim": "#111317",
        "on-secondary-fixed": "#002109",
        "on-primary-container": "#5c0008",
        "inverse-on-surface": "#2f3034",
        "error": "#ffb4ab",
        "outline-variant": "#5b403e",
        "surface-container-low": "#1a1c1f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "12px",
        "xl": "80px",
        "md": "24px",
        "lg": "48px",
        "xs": "4px",
        "base": "8px",
        "container-max": "1440px",
        "gutter": "24px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "title-md": ["Outfit", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"]
      },
      fontSize: {
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    },
  },
  plugins: [
    import('@tailwindcss/forms'),
  ],
}
